apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: ObjectStore
metadata:
  name: objectstore-sample
spec:
  config:
    valueFrom:
      secretKeyRef:
        name: my-objectstore-secret
  compactor:
    enabled: true
  bucketWeb:
    enabled: true
